# Generated by Django 3.0.5 on 2020-04-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landtransaction',
            name='date_of_transfer',
            field=models.DateTimeField(),
        ),
    ]
